#!/bin/bash

rm -f cfi_blacklist  *.o

BLACKLIST="/store/artem/git/osquery-lto/tools/analysis/cfi_blacklist.txt"
#BLACKLIST="`pwd`/blacklist/cfi_blacklist.txt"
#ARGS_BLOK="  -DBOOST_NETWORK_ENABLE_HTTPS -DBOOST_NO_CXX11_VARIADIC_TEMPLATES -DDEBIAN_BASED=1 -DNDEBUG -DOSQUERY_BUILD_DISTRO=xenial -DOSQUERY_BUILD_PLATFORM=ubuntu -DOSQUERY_BUILD_SDK_VERSION=2.2.1 -DOSQUERY_THRIFT=\"\" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSTRIP_FLAG_HELP=1 -DUBUNTU -DUBUNTU_XENIAL -isystem /store/artem/git/osquery-lto/third-party/sysroots/linux -isystem /usr/local/osquery/legacy/include -isystem /usr/local/osquery/include -I/usr/local/osquery/include/openssl -I/store/artem/git/osquery-lto/third-party/sqlite3 -I/store/artem/git/osquery-lto/include -I/store/artem/git/osquery-lto -I/store/artem/git/osquery-lto/build/xenial/generated/gen-cpp  -L/usr/local/osquery/lib     -std=c++14 -stdlib=libstdc++ -Qunused-arguments -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -pipe -fdata-sections -ffunction-sections -fsanitize-blacklist=${BLACKLIST} -flto -fsanitize=cfi -fsanitize-cfi-cross-dso -fno-sanitize-trap=all -fvisibility=default -D_GLIBCXX_USE_CXX11_ABI=1 -Os -fPIE -fpie -fPIC -fpic -march=x86-64 -mno-avx -Wall -Wextra -Wshadow -pedantic -Wuseless-cast -Wno-c99-extensions -Wno-zero-length-array -Wno-unused-parameter -Wno-gnu-case-range"
#ARGS_BLFAIL="-DBOOST_NETWORK_ENABLE_HTTPS -DBOOST_NO_CXX11_VARIADIC_TEMPLATES -DDEBIAN_BASED=1 -DNDEBUG -DOSQUERY_BUILD_DISTRO=xenial -DOSQUERY_BUILD_PLATFORM=ubuntu -DOSQUERY_BUILD_SDK_VERSION=2.2.1 -DOSQUERY_THRIFT=\"\" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSTRIP_FLAG_HELP=1 -DUBUNTU -DUBUNTU_XENIAL -isystem /store/artem/git/osquery-lto/third-party/sysroots/linux -isystem /usr/local/osquery/legacy/include -isystem /usr/local/osquery/include -I/usr/local/osquery/include/openssl -I/store/artem/git/osquery-lto/third-party/sqlite3 -I/store/artem/git/osquery-lto/include -I/store/artem/git/osquery-lto -I/store/artem/git/osquery-lto/build/xenial/generated/gen-cpp  -L/usr/local/osquery/lib     -std=c++14 -stdlib=libstdc++ -Qunused-arguments -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -pipe -fdata-sections -ffunction-sections -flto -fsanitize=cfi -fsanitize-cfi-cross-dso -fno-sanitize-trap=all -fvisibility=default -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST} -Os -fPIE -fpie -fPIC -fpic -march=x86-64 -mno-avx -Wall -Wextra -Wshadow -pedantic -Wuseless-cast -Wno-c99-extensions -Wno-zero-length-array -Wno-unused-parameter -Wno-gnu-case-range"
#LINKARGS="-L/usr/local/osquery/lib    -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST} -fno-sanitize-trap=all -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -flto"
#LINKARGS2="-L/usr/local/osquery/legacy/lib -rdynamic -Wl,-no-whole-archive -llinenoise /usr/local/osquery/legacy/lib/libz.so -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -lgflags -lthrift -lglog -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libdl.so /usr/local/osquery/legacy/lib/librt.so -lc -rdynamic -Wl,-zrelro -Wl,-znow -pie -lgcc_s -Wl,--build-id -static-libstdc++ -Wl,-Bstatic -lcppnetlib-uri -lcppnetlib-client-connections -lboost_regex-mt -lrocksdb_lite -lsnappy -lssl -lyara -lcrypto -Wl,-Bdynamic -lpthread -Wl,-Bstatic -llinenoise -ludev -laudit -laws-cpp-sdk-kinesis -laws-cpp-sdk-firehose -laws-cpp-sdk-sts -laws-cpp-sdk-core -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libresolv.so -Wl,-Bstatic -lcryptsetup -ldevmapper -lgcrypt -lgpg-error -lblkid -lip4tc -lmagic -ltsk -lapt-pkg -ldpkg -llz4 -llzma -lbz2 -lrpm -lrpmio -lbeecrypt -lpopt -ldb -laugeas -lfa -lxml2 -luuid -Wl,-Bdynamic"
#LINKARGS2="-L/usr/local/osquery/legacy/lib -rdynamic -Wl,-no-whole-archive -llinenoise /usr/local/osquery/legacy/lib/libz.so -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -lgflags -lthrift -lglog -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libdl.so /usr/local/osquery/legacy/lib/librt.so -lc -rdynamic -Wl,-zrelro -Wl,-znow -pie -lgcc_s -Wl,--build-id -static-libstdc++ -Wl,-Bstatic -lcppnetlib-uri -lcppnetlib-client-connections -lboost_regex-mt -lrocksdb_lite -lsnappy -lssl -lyara -lcrypto -Wl,-Bdynamic -lpthread"
#LINKARGS2="-L/usr/local/osquery/legacy/lib -rdynamic -Wl,-no-whole-archive -llinenoise /usr/local/osquery/legacy/lib/libz.so -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -lgflags -lthrift -lglog -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libdl.so /usr/local/osquery/legacy/lib/librt.so -lc -rdynamic -Wl,-zrelro -Wl,-znow -pie -lgcc_s -Wl,--build-id -static-libstdc++ -Wl,-Bdynamic -lpthread"
#LINKARGS2="-L/usr/local/osquery/legacy/lib -rdynamic -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -Wl,-Bdynamic -rdynamic -Wl,-zrelro -Wl,-znow -pie -lgcc_s -Wl,--build-id -static-libstdc++ -Wl,-Bdynamic -lpthread"
#LINKARGS2="-L/usr/local/osquery/legacy/lib  -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -rdynamic -pie -static-libstdc++ -Wl,-Bdynamic -lpthread"
#LINKARGS2="-lboost_system-mt -lboost_filesystem-mt -lpthread -static-libstdc++"

#ARGS="-g -DBOOST_NETWORK_ENABLE_HTTPS -DBOOST_NO_CXX11_VARIADIC_TEMPLATES -DDEBIAN_BASED=1 -DNDEBUG -DOSQUERY_BUILD_DISTRO=xenial -DOSQUERY_BUILD_PLATFORM=ubuntu -DOSQUERY_BUILD_SDK_VERSION=2.2.1 -DOSQUERY_THRIFT=\"\" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSTRIP_FLAG_HELP=1 -DUBUNTU -DUBUNTU_XENIAL -isystem /store/artem/git/osquery-lto/third-party/sysroots/linux -isystem /usr/local/osquery/legacy/include -isystem /usr/local/osquery/include -I/usr/local/osquery/include/openssl -I/store/artem/git/osquery-lto/third-party/sqlite3 -I/store/artem/git/osquery-lto/include -I/store/artem/git/osquery-lto -I/store/artem/git/osquery-lto/build/xenial/generated/gen-cpp  -L/usr/local/osquery/lib     -std=c++14 -stdlib=libstdc++ -Qunused-arguments -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-deprecated-register -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -pipe -fdata-sections -ffunction-sections -flto -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST} -O0 -fPIE -fpie -fPIC -fpic -march=x86-64 -mno-avx -Wall -Wextra -Wshadow -pedantic -Wuseless-cast -Wno-c99-extensions -Wno-zero-length-array -Wno-unused-parameter -Wno-gnu-case-range"
#LINKARGS="-L/usr/local/osquery/lib    -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST} -fno-sanitize-trap=all -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -flto"
#LINKARGS="-g -O0 -L/usr/local/osquery/lib    -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST} -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -flto"
#LINKARGS2="-L/usr/local/osquery/legacy/lib -rdynamic -Wl,-no-whole-archive -llinenoise /usr/local/osquery/legacy/lib/libz.so -Wl,-Bstatic -lboost_system-mt -lboost_filesystem-mt -lgflags -lthrift -lglog -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libdl.so /usr/local/osquery/legacy/lib/librt.so -lc -rdynamic -Wl,-zrelro -Wl,-znow -pie -lgcc_s -Wl,--build-id -static-libstdc++ -Wl,-Bstatic -lcppnetlib-uri -lcppnetlib-client-connections -lboost_regex-mt -lrocksdb_lite -lsnappy -lssl -lyara -lcrypto -Wl,-Bdynamic -lpthread -Wl,-Bstatic -llinenoise -ludev -laudit -laws-cpp-sdk-kinesis -laws-cpp-sdk-firehose -laws-cpp-sdk-sts -laws-cpp-sdk-core -Wl,-Bdynamic /usr/local/osquery/legacy/lib/libresolv.so -Wl,-Bstatic -lcryptsetup -ldevmapper -lgcrypt -lgpg-error -lblkid -lip4tc -lmagic -ltsk -lapt-pkg -ldpkg -llz4 -llzma -lbz2 -lrpm -lrpmio -lbeecrypt -lpopt -ldb -laugeas -lfa -lxml2 -luuid -Wl,-Bdynamic"

ARGS=" -std=c++14 -fno-sanitize-trap=all -flto -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST}"
LINKARGS=" -fno-sanitize-trap=all -flto -fsanitize=cfi -fsanitize-cfi-cross-dso -fvisibility=default -D_GLIBCXX_USE_CXX11_ABI=1 -fsanitize-blacklist=${BLACKLIST}"
LINKARGS2="-lboost_system-mt -lboost_filesystem-mt -lpthread -static-libstdc++"
/usr/local/osquery/bin/clang++  -I/usr/local/osquery/include -I. ${ARGS} -c -o config.o config.cpp
/usr/local/osquery/bin/clang++  -I/usr/local/osquery/include -I. ${ARGS} -c -o registry.o registry.cpp
/usr/local/osquery/bin/clang++  -L/usr/local/osquery/lib -I/usr/local/osquery/include -I. ${LINKARGS} -o cfi_blacklist config.o registry.o ${LINKARGS2}

# /usr/local/osquery/bin/clang++  -I/usr/local/osquery/include -I. ${ARGS_BLFAIL} -c -o config_blfail.o config.cpp
# /usr/local/osquery/bin/clang++  -I/usr/local/osquery/include -I. ${ARGS_BLFAIL} -c -o registry_blfail.o registry.cpp
# /usr/local/osquery/bin/clang++  -L/usr/local/osquery/lib -I/usr/local/osquery/include -I. ${LINKARGS} -o blacklist_fail config_blfail.o registry_blfail.o ${LINKARGS2}
